app/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField, BooleanField
from wtforms.validators import DataRequired, Email, Length


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Sign in")


class TaskForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired(), Length(min=5, max=255)])
    email = StringField("Email", validators=[Email()])
    submit = SubmitField("Create task")


class EditTaskForm(FlaskForm):
    text = TextAreaField("Text", validators=[DataRequired(), Length(5, 255)])
    status = BooleanField("Status")
    submit = SubmitField("Change")

app/__init__.py
import logging
import os
from logging.handlers import RotatingFileHandler

from flask import Flask, request, current_app
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate

from app.config import Config

migrate = Migrate()
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    migrate.init_app(app)
    bootstrap.init_app(app)

    from app.errors import bp as errors_bp

    app.register_blueprint(errors_bp)

    from app.tasks import bp as tasks_bp

    app.register_blueprint(tasks_bp)

    if not app.debug and not app.testing:
        if not os.path.exists("logs"):
            os.mkdir("logs")
        file_handler = RotatingFileHandler("logs/tasks.log", maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
        app.logger.setLevel(logging.INFO)
        app.logger.info("Tasks startup")

    return app

app/api/__init__.py
from app.api.exceptions import ApiException
from app.api.api import Api
from app.api.sort_direction import SortDirection
from app.api.sort_field import SortField
from app.api.task_status import TaskStatus

app/tasks/__init__.py
from flask import Blueprint

bp = Blueprint("tasks", __name__)

from app.tasks import routes

app/tasks/routes.py
from flask import request, session, redirect, url_for, render_template, flash
from app.tasks.wrappers import require_api_token
from app.api import Api, SortField, SortDirection, TaskStatus
from app.tasks.services.task_service import TaskService
from app.tasks.forms import LoginForm, TaskForm, EditTaskForm
from app.api.exceptions import ApiAuthorizationException, TokenExpiredException

from app.tasks import bp


@bp.route("/login", methods=["GET", "POST"])
def login():
    """
    Авторизация
    :return:
    """
    form = LoginForm()
    api = Api()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        try:
            data = api.login(username, password)
            token = data.get("token")
        except ApiAuthorizationException:
            flash("Incorrect auth data")
            return redirect(url_for("tasks.login"))
        session["token"] = token
        return redirect(url_for("tasks.index"))

    return render_template("tasks/login.html", title="Sign in", form=form)


@bp.route("/logout")
def logout():
    session["token"] = ""
    return redirect(url_for("tasks.index"))


@bp.route("/", methods=["GET", "POST"])
@bp.route("/index", methods=["GET", "POST"])
def index():
    """
    Все посты и добавление
    :return:
    """
    form = TaskForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        text = form.text.data
        Api.create_task(username, email, text)
        flash("Your task is now alive")
        return redirect(url_for("tasks.index"))

    page = request.args.get("page", 1, type=int)
    sort_field = request.args.get("sort_field", SortField.ID, type=str)
    sort_direction = request.args.get("sort_direction", SortDirection.ASC, type=str)

    tasks = TaskService.get_tasks(sort_field, sort_direction, str(page))
    next_url = url_for("tasks.index", page=page + 1, sort_field=sort_field,
                       sort_direction=sort_direction) if TaskService.has_next_page(page) else None
    prev_url = url_for("tasks.index", page=page - 1, sort_field=sort_field,
                       sort_direction=sort_direction) if page > 1 else None

    return render_template("index.html", title="Home", form=form, tasks=tasks, next_url=next_url,
                           prev_url=prev_url, SortDirection=SortDirection, SortField=SortField, sort_field=sort_field,
                           sort_direction=sort_direction, TaskStatus=TaskStatus)


@bp.route("/edit/<task_id>", methods=["GET", "POST"])
@require_api_token
def edit(task_id: int):
    """
    Редактирование задачи
    :param task_id:
    :return:
    """
    form = EditTaskForm()
    if form.validate_on_submit():
        text = form.text.data
        status = form.status.data
        try:
            TaskService.edit_task(task_id, session["token"], text, status)
        except TokenExpiredException:
            flash("Your token has been expired")
            return redirect(url_for("tasks.logout"))
        flash("Your changes has been saved")
        return redirect(url_for("tasks.index"))
    elif request.method == "GET":
        task_text = request.args.get("task_text")
        task_status = request.args.get("task_status")
        task_status = task_status in (TaskStatus.COMPLETED, TaskStatus.COMPLETED_EDITED)
        form.text.data = task_text
        form.status.data = task_status
    return render_template("tasks/edit_task.html", form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
{% if title %}{{ title }} - Tasks{% else %}Welcome to Tasks{% endif %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('tasks.index') }}">Tasks</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if not session.token %}
                <li><a href="{{ url_for('tasks.login') }}">Login</a></li>
                {% else %}
                <li><a href="{{ url_for('tasks.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block app_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
  <link rel="stylesheet" href="{{url_for('static', filename='tasks/css/style.css')}}">
{% endblock %}

{% block app_content %}
{% if form %}
{{ wtf.quick_form(form) }}
<br>
{% endif %}
<hr>
<label for="sort-direction">sort by</label>

<select name="sort-direction" id="sort-field">
<option value="{{ SortField.ID }}" {% if sort_field == SortField.ID %}selected="selected"{% endif %}>
    {{ SortField.description[SortField.ID] }}
</option>
<option value="{{ SortField.USERNAME }}" {% if sort_field == SortField.USERNAME %}selected="selected"{% endif %}>
    {{ SortField.description[SortField.USERNAME] }}
</option>
<option value="{{ SortField.STATUS }}" {% if sort_field == SortField.STATUS %}selected="selected"{% endif %}
    >{{ SortField.description[SortField.STATUS] }}
</option>
</select>

    <label for="sort-direction">direction </label>
<select name="sort-direction" id="sort-direction">
    <option value="{{ SortDirection.ASC }}" {% if sort_direction == SortDirection.ASC %}selected="selected"{% endif %}>
{{ SortDirection.description[SortDirection.ASC] }}</option>
    <option value="{{ SortDirection.DESC }}" {% if sort_direction == SortDirection.DESC %}selected="selected"{% endif %} >
{{ SortDirection.description[SortDirection.DESC] }}</option>
</select>
<button class="btn btn-primary" id="btn-sort">Apply</button>
<hr>
{% for task in tasks %}
{% include 'tasks/_task.html' %}
{% endfor %}

<nav aria-label="...">
    <ul class="pager">
       <li class="previous{% if not prev_url %} disabled{% endif %}">
           <a href="{{ prev_url or '#' }}">
               <span aria-hidden="true">&larr;</span> 
           </a>
       </li>
       <li class="next{% if not next_url %} disabled{% endif %}">
           <a href="{{ next_url or '#' }}">
               <span aria-hidden="true">&rarr;</span>
           </a>
       </li>
    </ul>
</nav>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='tasks/js/sort.js') }}"></script>
<script>
sort('{{ url_for("tasks.index") }}')
</script>
{% endblock %}

app/templates/tasks/_task.html
{% if task.status in (TaskStatus.COMPLETED, TaskStatus.COMPLETED_EDITED)%}
    {% set status_icon %}
        <span class="glyphicon glyphicon-ok-circle" style="color: green"></span>
        <small style="color: green;">{{ TaskStatus.description.get(task.status) }}</small>
    {% endset %}
{% else %}
    {% set status_icon %}
        <span class="glyphicon glyphicon-remove-circle" style="color: red"></span>
        <small style="color: red;">{{ TaskStatus.description.get(task.status) }}</small>
    {% endset %}
{% endif %}

<div class="panel panel-primary">
    <div class="panel-heading panel-heading_justify">
        <h3 class="panel-title">{{ task.username }}-{{ task.email }}</h3>
        {% if session.get("token") %}
        <a href="{{ url_for('tasks.edit', task_id=task.id, task_text=task.text, task_status=task.status) }}"
           style="display: block;">
            <span class="glyphicon glyphicon-pencil"></span>
            {% endif %}
        </a>
    </div>
    <div class="panel-body">
        <div>
            {{ task.text }}
        </div>
        <div>
            {{ status_icon }}
        </div>
    </div>
</div>

app/templates/tasks/edit_task.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<h1>Edit Task</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>

{% endblock %}

app/templates/tasks/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Sign In</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
 {% endblock %}